# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[30,)" #mandatory (28 is current forge version)

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="structure_tutorial" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory

 # A display name for the mod
displayName="Structure Tutorial Mod" #mandatory

# A text field displayed in the mod UI
credits="" #optional

# A text field displayed in the mod UI
authors="TelepathicGrunt" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A short mod example on how to register structures and generate them in any biome using structure nbt files.
'''