modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory (32 is current forge version)
license="MIT License"

[[mods]] #mandatory
modId="structure_tutorial" #mandatory
version="${version}" #mandatory
displayName="Structure Tutorial Mod" #mandatory
credits="Special thanks to nhwhite3118 for helping out!"
authors="TelepathicGrunt" #optional
description='''
A short mod example on how to register structures and generate them in any biome using structure nbt files.
'''

# makes sure our mod does not be attempted to be ran on older version of Minecraft and explodes
[[dependencies.structure_tutorial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17.0)"